name: ci
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
      - user: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Rodar o lint
        nun: npm run lint

      - name: Rodar o teste
        run: npm run test

      - name: Buildar a aplicacao
        run: npm run build
